apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rockbot.agentPvcName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rockbot.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.agentDataSize }}
